/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vrp_solver_CONSTANTS_H
#define vrp_solver_CONSTANTS_H

#include "vrp_solver_types.h"



class vrp_solverConstants {
 public:
  vrp_solverConstants();

};

extern const vrp_solverConstants g_vrp_solver_constants;



#endif
