/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vrp_solver_constants.h"



const vrp_solverConstants g_vrp_solver_constants;

vrp_solverConstants::vrp_solverConstants() {
}



