/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VRPSolver_H
#define VRPSolver_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "vrp_solver_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class VRPSolverIf {
 public:
  virtual ~VRPSolverIf() {}
  virtual void solveCVRP(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm) = 0;
  virtual void solveCVRPTW(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm) = 0;
  virtual void solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm) = 0;
  virtual void solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm) = 0;
};

class VRPSolverIfFactory {
 public:
  typedef VRPSolverIf Handler;

  virtual ~VRPSolverIfFactory() {}

  virtual VRPSolverIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(VRPSolverIf* /* handler */) = 0;
};

class VRPSolverIfSingletonFactory : virtual public VRPSolverIfFactory {
 public:
  VRPSolverIfSingletonFactory(const boost::shared_ptr<VRPSolverIf>& iface) : iface_(iface) {}
  virtual ~VRPSolverIfSingletonFactory() {}

  virtual VRPSolverIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(VRPSolverIf* /* handler */) {}

 protected:
  boost::shared_ptr<VRPSolverIf> iface_;
};

class VRPSolverNull : virtual public VRPSolverIf {
 public:
  virtual ~VRPSolverNull() {}
  void solveCVRP(std::vector<std::vector<int64_t> > & /* _return */, const std::vector<std::vector<int64_t> > & /* vec */, const std::vector<int64_t> & /* demands */, const std::vector<int64_t> & /* v_caps */, const int64_t /* lns */, const int64_t /* tm */) {
    return;
  }
  void solveCVRPTW(std::vector<std::vector<int64_t> > & /* _return */, const std::vector<std::vector<int64_t> > & /* vec */, const std::vector<int64_t> & /* demands */, const std::vector<int64_t> & /* v_caps */, const std::vector<std::vector<int64_t> > & /* timeWindows */, const std::vector<int64_t> & /* serviceTime */, const int64_t /* lns */, const int64_t /* tm */) {
    return;
  }
  void solveCVRPTWMD(std::vector<std::vector<int64_t> > & /* _return */, const std::vector<std::vector<int64_t> > & /* vec */, const std::vector<int64_t> & /* demands */, const std::vector<int64_t> & /* v_caps */, const std::vector<std::vector<int64_t> > & /* timeWindows */, const std::vector<int64_t> & /* serviceTime */, const std::vector<std::vector<int64_t> > & /* depots */, const int64_t /* lns */, const int64_t /* tm */) {
    return;
  }
  void solveCVRPTWPD(std::vector<std::vector<int64_t> > & /* _return */, const std::vector<std::vector<int64_t> > & /* vec */, const std::vector<int64_t> & /* demands */, const std::vector<int64_t> & /* v_caps */, const std::vector<std::vector<int64_t> > & /* timeWindows */, const std::vector<int64_t> & /* serviceTime */, const std::vector<int64_t> & /* pickups */, const std::vector<int64_t> & /* delivs */, const int64_t /* lns */, const int64_t /* tm */) {
    return;
  }
};

typedef struct _VRPSolver_solveCVRP_args__isset {
  _VRPSolver_solveCVRP_args__isset() : vec(false), demands(false), v_caps(false), lns(false), tm(false) {}
  bool vec :1;
  bool demands :1;
  bool v_caps :1;
  bool lns :1;
  bool tm :1;
} _VRPSolver_solveCVRP_args__isset;

class VRPSolver_solveCVRP_args {
 public:

  VRPSolver_solveCVRP_args(const VRPSolver_solveCVRP_args&);
  VRPSolver_solveCVRP_args& operator=(const VRPSolver_solveCVRP_args&);
  VRPSolver_solveCVRP_args() : lns(0), tm(0) {
  }

  virtual ~VRPSolver_solveCVRP_args() throw();
  std::vector<std::vector<int64_t> >  vec;
  std::vector<int64_t>  demands;
  std::vector<int64_t>  v_caps;
  int64_t lns;
  int64_t tm;

  _VRPSolver_solveCVRP_args__isset __isset;

  void __set_vec(const std::vector<std::vector<int64_t> > & val);

  void __set_demands(const std::vector<int64_t> & val);

  void __set_v_caps(const std::vector<int64_t> & val);

  void __set_lns(const int64_t val);

  void __set_tm(const int64_t val);

  bool operator == (const VRPSolver_solveCVRP_args & rhs) const
  {
    if (!(vec == rhs.vec))
      return false;
    if (!(demands == rhs.demands))
      return false;
    if (!(v_caps == rhs.v_caps))
      return false;
    if (!(lns == rhs.lns))
      return false;
    if (!(tm == rhs.tm))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRP_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRP_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VRPSolver_solveCVRP_pargs {
 public:


  virtual ~VRPSolver_solveCVRP_pargs() throw();
  const std::vector<std::vector<int64_t> > * vec;
  const std::vector<int64_t> * demands;
  const std::vector<int64_t> * v_caps;
  const int64_t* lns;
  const int64_t* tm;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRP_result__isset {
  _VRPSolver_solveCVRP_result__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRP_result__isset;

class VRPSolver_solveCVRP_result {
 public:

  VRPSolver_solveCVRP_result(const VRPSolver_solveCVRP_result&);
  VRPSolver_solveCVRP_result& operator=(const VRPSolver_solveCVRP_result&);
  VRPSolver_solveCVRP_result() {
  }

  virtual ~VRPSolver_solveCVRP_result() throw();
  std::vector<std::vector<int64_t> >  success;

  _VRPSolver_solveCVRP_result__isset __isset;

  void __set_success(const std::vector<std::vector<int64_t> > & val);

  bool operator == (const VRPSolver_solveCVRP_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRP_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRP_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRP_presult__isset {
  _VRPSolver_solveCVRP_presult__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRP_presult__isset;

class VRPSolver_solveCVRP_presult {
 public:


  virtual ~VRPSolver_solveCVRP_presult() throw();
  std::vector<std::vector<int64_t> > * success;

  _VRPSolver_solveCVRP_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VRPSolver_solveCVRPTW_args__isset {
  _VRPSolver_solveCVRPTW_args__isset() : vec(false), demands(false), v_caps(false), timeWindows(false), serviceTime(false), lns(false), tm(false) {}
  bool vec :1;
  bool demands :1;
  bool v_caps :1;
  bool timeWindows :1;
  bool serviceTime :1;
  bool lns :1;
  bool tm :1;
} _VRPSolver_solveCVRPTW_args__isset;

class VRPSolver_solveCVRPTW_args {
 public:

  VRPSolver_solveCVRPTW_args(const VRPSolver_solveCVRPTW_args&);
  VRPSolver_solveCVRPTW_args& operator=(const VRPSolver_solveCVRPTW_args&);
  VRPSolver_solveCVRPTW_args() : lns(0), tm(0) {
  }

  virtual ~VRPSolver_solveCVRPTW_args() throw();
  std::vector<std::vector<int64_t> >  vec;
  std::vector<int64_t>  demands;
  std::vector<int64_t>  v_caps;
  std::vector<std::vector<int64_t> >  timeWindows;
  std::vector<int64_t>  serviceTime;
  int64_t lns;
  int64_t tm;

  _VRPSolver_solveCVRPTW_args__isset __isset;

  void __set_vec(const std::vector<std::vector<int64_t> > & val);

  void __set_demands(const std::vector<int64_t> & val);

  void __set_v_caps(const std::vector<int64_t> & val);

  void __set_timeWindows(const std::vector<std::vector<int64_t> > & val);

  void __set_serviceTime(const std::vector<int64_t> & val);

  void __set_lns(const int64_t val);

  void __set_tm(const int64_t val);

  bool operator == (const VRPSolver_solveCVRPTW_args & rhs) const
  {
    if (!(vec == rhs.vec))
      return false;
    if (!(demands == rhs.demands))
      return false;
    if (!(v_caps == rhs.v_caps))
      return false;
    if (!(timeWindows == rhs.timeWindows))
      return false;
    if (!(serviceTime == rhs.serviceTime))
      return false;
    if (!(lns == rhs.lns))
      return false;
    if (!(tm == rhs.tm))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTW_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTW_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VRPSolver_solveCVRPTW_pargs {
 public:


  virtual ~VRPSolver_solveCVRPTW_pargs() throw();
  const std::vector<std::vector<int64_t> > * vec;
  const std::vector<int64_t> * demands;
  const std::vector<int64_t> * v_caps;
  const std::vector<std::vector<int64_t> > * timeWindows;
  const std::vector<int64_t> * serviceTime;
  const int64_t* lns;
  const int64_t* tm;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTW_result__isset {
  _VRPSolver_solveCVRPTW_result__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTW_result__isset;

class VRPSolver_solveCVRPTW_result {
 public:

  VRPSolver_solveCVRPTW_result(const VRPSolver_solveCVRPTW_result&);
  VRPSolver_solveCVRPTW_result& operator=(const VRPSolver_solveCVRPTW_result&);
  VRPSolver_solveCVRPTW_result() {
  }

  virtual ~VRPSolver_solveCVRPTW_result() throw();
  std::vector<std::vector<int64_t> >  success;

  _VRPSolver_solveCVRPTW_result__isset __isset;

  void __set_success(const std::vector<std::vector<int64_t> > & val);

  bool operator == (const VRPSolver_solveCVRPTW_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTW_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTW_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTW_presult__isset {
  _VRPSolver_solveCVRPTW_presult__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTW_presult__isset;

class VRPSolver_solveCVRPTW_presult {
 public:


  virtual ~VRPSolver_solveCVRPTW_presult() throw();
  std::vector<std::vector<int64_t> > * success;

  _VRPSolver_solveCVRPTW_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VRPSolver_solveCVRPTWMD_args__isset {
  _VRPSolver_solveCVRPTWMD_args__isset() : vec(false), demands(false), v_caps(false), timeWindows(false), serviceTime(false), depots(false), lns(false), tm(false) {}
  bool vec :1;
  bool demands :1;
  bool v_caps :1;
  bool timeWindows :1;
  bool serviceTime :1;
  bool depots :1;
  bool lns :1;
  bool tm :1;
} _VRPSolver_solveCVRPTWMD_args__isset;

class VRPSolver_solveCVRPTWMD_args {
 public:

  VRPSolver_solveCVRPTWMD_args(const VRPSolver_solveCVRPTWMD_args&);
  VRPSolver_solveCVRPTWMD_args& operator=(const VRPSolver_solveCVRPTWMD_args&);
  VRPSolver_solveCVRPTWMD_args() : lns(0), tm(0) {
  }

  virtual ~VRPSolver_solveCVRPTWMD_args() throw();
  std::vector<std::vector<int64_t> >  vec;
  std::vector<int64_t>  demands;
  std::vector<int64_t>  v_caps;
  std::vector<std::vector<int64_t> >  timeWindows;
  std::vector<int64_t>  serviceTime;
  std::vector<std::vector<int64_t> >  depots;
  int64_t lns;
  int64_t tm;

  _VRPSolver_solveCVRPTWMD_args__isset __isset;

  void __set_vec(const std::vector<std::vector<int64_t> > & val);

  void __set_demands(const std::vector<int64_t> & val);

  void __set_v_caps(const std::vector<int64_t> & val);

  void __set_timeWindows(const std::vector<std::vector<int64_t> > & val);

  void __set_serviceTime(const std::vector<int64_t> & val);

  void __set_depots(const std::vector<std::vector<int64_t> > & val);

  void __set_lns(const int64_t val);

  void __set_tm(const int64_t val);

  bool operator == (const VRPSolver_solveCVRPTWMD_args & rhs) const
  {
    if (!(vec == rhs.vec))
      return false;
    if (!(demands == rhs.demands))
      return false;
    if (!(v_caps == rhs.v_caps))
      return false;
    if (!(timeWindows == rhs.timeWindows))
      return false;
    if (!(serviceTime == rhs.serviceTime))
      return false;
    if (!(depots == rhs.depots))
      return false;
    if (!(lns == rhs.lns))
      return false;
    if (!(tm == rhs.tm))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTWMD_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTWMD_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VRPSolver_solveCVRPTWMD_pargs {
 public:


  virtual ~VRPSolver_solveCVRPTWMD_pargs() throw();
  const std::vector<std::vector<int64_t> > * vec;
  const std::vector<int64_t> * demands;
  const std::vector<int64_t> * v_caps;
  const std::vector<std::vector<int64_t> > * timeWindows;
  const std::vector<int64_t> * serviceTime;
  const std::vector<std::vector<int64_t> > * depots;
  const int64_t* lns;
  const int64_t* tm;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTWMD_result__isset {
  _VRPSolver_solveCVRPTWMD_result__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTWMD_result__isset;

class VRPSolver_solveCVRPTWMD_result {
 public:

  VRPSolver_solveCVRPTWMD_result(const VRPSolver_solveCVRPTWMD_result&);
  VRPSolver_solveCVRPTWMD_result& operator=(const VRPSolver_solveCVRPTWMD_result&);
  VRPSolver_solveCVRPTWMD_result() {
  }

  virtual ~VRPSolver_solveCVRPTWMD_result() throw();
  std::vector<std::vector<int64_t> >  success;

  _VRPSolver_solveCVRPTWMD_result__isset __isset;

  void __set_success(const std::vector<std::vector<int64_t> > & val);

  bool operator == (const VRPSolver_solveCVRPTWMD_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTWMD_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTWMD_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTWMD_presult__isset {
  _VRPSolver_solveCVRPTWMD_presult__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTWMD_presult__isset;

class VRPSolver_solveCVRPTWMD_presult {
 public:


  virtual ~VRPSolver_solveCVRPTWMD_presult() throw();
  std::vector<std::vector<int64_t> > * success;

  _VRPSolver_solveCVRPTWMD_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VRPSolver_solveCVRPTWPD_args__isset {
  _VRPSolver_solveCVRPTWPD_args__isset() : vec(false), demands(false), v_caps(false), timeWindows(false), serviceTime(false), pickups(false), delivs(false), lns(false), tm(false) {}
  bool vec :1;
  bool demands :1;
  bool v_caps :1;
  bool timeWindows :1;
  bool serviceTime :1;
  bool pickups :1;
  bool delivs :1;
  bool lns :1;
  bool tm :1;
} _VRPSolver_solveCVRPTWPD_args__isset;

class VRPSolver_solveCVRPTWPD_args {
 public:

  VRPSolver_solveCVRPTWPD_args(const VRPSolver_solveCVRPTWPD_args&);
  VRPSolver_solveCVRPTWPD_args& operator=(const VRPSolver_solveCVRPTWPD_args&);
  VRPSolver_solveCVRPTWPD_args() : lns(0), tm(0) {
  }

  virtual ~VRPSolver_solveCVRPTWPD_args() throw();
  std::vector<std::vector<int64_t> >  vec;
  std::vector<int64_t>  demands;
  std::vector<int64_t>  v_caps;
  std::vector<std::vector<int64_t> >  timeWindows;
  std::vector<int64_t>  serviceTime;
  std::vector<int64_t>  pickups;
  std::vector<int64_t>  delivs;
  int64_t lns;
  int64_t tm;

  _VRPSolver_solveCVRPTWPD_args__isset __isset;

  void __set_vec(const std::vector<std::vector<int64_t> > & val);

  void __set_demands(const std::vector<int64_t> & val);

  void __set_v_caps(const std::vector<int64_t> & val);

  void __set_timeWindows(const std::vector<std::vector<int64_t> > & val);

  void __set_serviceTime(const std::vector<int64_t> & val);

  void __set_pickups(const std::vector<int64_t> & val);

  void __set_delivs(const std::vector<int64_t> & val);

  void __set_lns(const int64_t val);

  void __set_tm(const int64_t val);

  bool operator == (const VRPSolver_solveCVRPTWPD_args & rhs) const
  {
    if (!(vec == rhs.vec))
      return false;
    if (!(demands == rhs.demands))
      return false;
    if (!(v_caps == rhs.v_caps))
      return false;
    if (!(timeWindows == rhs.timeWindows))
      return false;
    if (!(serviceTime == rhs.serviceTime))
      return false;
    if (!(pickups == rhs.pickups))
      return false;
    if (!(delivs == rhs.delivs))
      return false;
    if (!(lns == rhs.lns))
      return false;
    if (!(tm == rhs.tm))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTWPD_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTWPD_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VRPSolver_solveCVRPTWPD_pargs {
 public:


  virtual ~VRPSolver_solveCVRPTWPD_pargs() throw();
  const std::vector<std::vector<int64_t> > * vec;
  const std::vector<int64_t> * demands;
  const std::vector<int64_t> * v_caps;
  const std::vector<std::vector<int64_t> > * timeWindows;
  const std::vector<int64_t> * serviceTime;
  const std::vector<int64_t> * pickups;
  const std::vector<int64_t> * delivs;
  const int64_t* lns;
  const int64_t* tm;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTWPD_result__isset {
  _VRPSolver_solveCVRPTWPD_result__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTWPD_result__isset;

class VRPSolver_solveCVRPTWPD_result {
 public:

  VRPSolver_solveCVRPTWPD_result(const VRPSolver_solveCVRPTWPD_result&);
  VRPSolver_solveCVRPTWPD_result& operator=(const VRPSolver_solveCVRPTWPD_result&);
  VRPSolver_solveCVRPTWPD_result() {
  }

  virtual ~VRPSolver_solveCVRPTWPD_result() throw();
  std::vector<std::vector<int64_t> >  success;

  _VRPSolver_solveCVRPTWPD_result__isset __isset;

  void __set_success(const std::vector<std::vector<int64_t> > & val);

  bool operator == (const VRPSolver_solveCVRPTWPD_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VRPSolver_solveCVRPTWPD_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VRPSolver_solveCVRPTWPD_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VRPSolver_solveCVRPTWPD_presult__isset {
  _VRPSolver_solveCVRPTWPD_presult__isset() : success(false) {}
  bool success :1;
} _VRPSolver_solveCVRPTWPD_presult__isset;

class VRPSolver_solveCVRPTWPD_presult {
 public:


  virtual ~VRPSolver_solveCVRPTWPD_presult() throw();
  std::vector<std::vector<int64_t> > * success;

  _VRPSolver_solveCVRPTWPD_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class VRPSolverClient : virtual public VRPSolverIf {
 public:
  VRPSolverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  VRPSolverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void solveCVRP(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm);
  void send_solveCVRP(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm);
  void recv_solveCVRP(std::vector<std::vector<int64_t> > & _return);
  void solveCVRPTW(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm);
  void send_solveCVRPTW(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTW(std::vector<std::vector<int64_t> > & _return);
  void solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm);
  void send_solveCVRPTWMD(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return);
  void solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm);
  void send_solveCVRPTWPD(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class VRPSolverProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<VRPSolverIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (VRPSolverProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_solveCVRP(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_solveCVRPTW(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_solveCVRPTWMD(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_solveCVRPTWPD(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  VRPSolverProcessor(boost::shared_ptr<VRPSolverIf> iface) :
    iface_(iface) {
    processMap_["solveCVRP"] = &VRPSolverProcessor::process_solveCVRP;
    processMap_["solveCVRPTW"] = &VRPSolverProcessor::process_solveCVRPTW;
    processMap_["solveCVRPTWMD"] = &VRPSolverProcessor::process_solveCVRPTWMD;
    processMap_["solveCVRPTWPD"] = &VRPSolverProcessor::process_solveCVRPTWPD;
  }

  virtual ~VRPSolverProcessor() {}
};

class VRPSolverProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  VRPSolverProcessorFactory(const ::boost::shared_ptr< VRPSolverIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< VRPSolverIfFactory > handlerFactory_;
};

class VRPSolverMultiface : virtual public VRPSolverIf {
 public:
  VRPSolverMultiface(std::vector<boost::shared_ptr<VRPSolverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~VRPSolverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<VRPSolverIf> > ifaces_;
  VRPSolverMultiface() {}
  void add(boost::shared_ptr<VRPSolverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void solveCVRP(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->solveCVRP(_return, vec, demands, v_caps, lns, tm);
    }
    ifaces_[i]->solveCVRP(_return, vec, demands, v_caps, lns, tm);
    return;
  }

  void solveCVRPTW(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->solveCVRPTW(_return, vec, demands, v_caps, timeWindows, serviceTime, lns, tm);
    }
    ifaces_[i]->solveCVRPTW(_return, vec, demands, v_caps, timeWindows, serviceTime, lns, tm);
    return;
  }

  void solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->solveCVRPTWMD(_return, vec, demands, v_caps, timeWindows, serviceTime, depots, lns, tm);
    }
    ifaces_[i]->solveCVRPTWMD(_return, vec, demands, v_caps, timeWindows, serviceTime, depots, lns, tm);
    return;
  }

  void solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->solveCVRPTWPD(_return, vec, demands, v_caps, timeWindows, serviceTime, pickups, delivs, lns, tm);
    }
    ifaces_[i]->solveCVRPTWPD(_return, vec, demands, v_caps, timeWindows, serviceTime, pickups, delivs, lns, tm);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class VRPSolverConcurrentClient : virtual public VRPSolverIf {
 public:
  VRPSolverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  VRPSolverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void solveCVRP(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm);
  int32_t send_solveCVRP(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const int64_t lns, const int64_t tm);
  void recv_solveCVRP(std::vector<std::vector<int64_t> > & _return, const int32_t seqid);
  void solveCVRPTW(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm);
  int32_t send_solveCVRPTW(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTW(std::vector<std::vector<int64_t> > & _return, const int32_t seqid);
  void solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm);
  int32_t send_solveCVRPTWMD(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<std::vector<int64_t> > & depots, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTWMD(std::vector<std::vector<int64_t> > & _return, const int32_t seqid);
  void solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return, const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm);
  int32_t send_solveCVRPTWPD(const std::vector<std::vector<int64_t> > & vec, const std::vector<int64_t> & demands, const std::vector<int64_t> & v_caps, const std::vector<std::vector<int64_t> > & timeWindows, const std::vector<int64_t> & serviceTime, const std::vector<int64_t> & pickups, const std::vector<int64_t> & delivs, const int64_t lns, const int64_t tm);
  void recv_solveCVRPTWPD(std::vector<std::vector<int64_t> > & _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
